#ifndef DIFFLOGGING_H
#define DIFFLOGGING_H

#include <qloggingcategory.h>

Q_DECLARE_LOGGING_CATEGORY(logDiff);
Q_DECLARE_LOGGING_CATEGORY(logLinesParser);
Q_DECLARE_LOGGING_CATEGORY(logScriptTable);
Q_DECLARE_LOGGING_CATEGORY(logDatTable);
Q_DECLARE_LOGGING_CATEGORY(logRecordParser);
Q_DECLARE_LOGGING_CATEGORY(logLinesParserMain);
Q_DECLARE_LOGGING_CATEGORY(logTableLinks);
Q_DECLARE_LOGGING_CATEGORY(logJoin);
Q_DECLARE_LOGGING_CATEGORY(logSqlScriptMain);
Q_DECLARE_LOGGING_CATEGORY(logJoinTable);
Q_DECLARE_LOGGING_CATEGORY(logJoinTables);
Q_DECLARE_LOGGING_CATEGORY(logTask);

#endif // DIFFLOGGING_H
