#ifndef LOGGINGCATEGORIES_H
#define LOGGINGCATEGORIES_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logCore)
Q_DECLARE_LOGGING_CATEGORY(logSql)
Q_DECLARE_LOGGING_CATEGORY(logFmt)
Q_DECLARE_LOGGING_CATEGORY(logDbgHelp)

#endif // LOGGINGCATEGORIES_H
