/*
$Author: Serpkov
$Description: Макрос с объявлениями глобальных переменных
$ShowReport: true
$Highlighter: sql
*/

import "fmtglobals.mac", fmt, StdDialogs, ToolsRuntime;

macro ExecAction()
    debugbreak;

    /*var haswindow = fmtAppHasTableWindow("dparty_dbt");

    if (haswindow)
        msgInformation("информация", "Окно есть");
    else
        msgCritical("информация", "Окна нет");
    end;*/

    /*var haswindow = fmtappOpenTableWindow("dparty_dbt");

    var table = haswindow.table;
    var selected = fmtSelectTableFieldsDailog(table, "Выбор полей: ");

    println(selected);*/

    //var wnd = fmtappConnectionWindows({CurrentConnection});
    println(fmt.fmtTableSqlText({FmtTable}));
end;