import "fmtglobals.mac", fmt, StdDialogs;

macro ExecAction()
    debugbreak;

    /*var haswindow = fmtAppHasTableWindow("dparty_dbt");

    if (haswindow)
        msgInformation("информация", "Окно есть");
    else
        msgCritical("информация", "Окна нет");
    end;*/

    var haswindow = fmtappOpenTableWindow("dparty_dbt");

    var table = haswindow.table;
    var selected = fmtSelectTableFieldsDailog(table, "Выбор полей: ");

    println(selected);
end;