CREATE TABLE "FMT_NAMES" (
"T_ID"  REAL(10) NOT NULL,
"T_NAME"  TEXT(30) NOT NULL,
"T_CACHESIZE"  REAL(10),
"T_OWNER"  TEXT(9),
"T_COMMENT"  TEXT(40),
"T_PKIDX"  REAL(5) NOT NULL,
"T_BLOBTYPE"  REAL(5) NOT NULL,
"T_BLOBLEN"  REAL(10) NOT NULL,
"T_FLAGS"  REAL(10) NOT NULL,
CONSTRAINT "names_u" UNIQUE ("T_ID")
)