CREATE TABLE "FMT_KEYS" (
"T_FMTID"  REAL(10) NOT NULL,
"T_KEYNUM"  REAL(10) NOT NULL,
"T_SEGNUM"  REAL(10) NOT NULL,
"T_FMTFLDID"  REAL(10) NOT NULL,
"T_FLAGS"  REAL(5) NOT NULL,
"T_TYPE"  REAL(10) NOT NULL,
"T_NULLVAL"  REAL(10) NOT NULL,
"T_ISREAL"  REAL(5) NOT NULL,
"T_COMMENT"  TEXT(128)
)