CREATE TABLE "FMT_FIELDS" (
"T_ID"  REAL(10) NOT NULL,
"T_FMTID"  REAL(10) NOT NULL,
"T_NAME"  TEXT(128) NOT NULL,
"T_TYPE"  REAL(10) NOT NULL,
"T_SIZE"  REAL(10) NOT NULL,
"T_OFFSET"  REAL(10) NOT NULL,
"T_OUTLEN"  REAL(5) NOT NULL,
"T_DECPOINT"  REAL(5) NOT NULL,
"T_HIDDEN"  TEXT(1) NOT NULL,
"T_COMMENT"  TEXT(128)
)