#ifndef VERSIONSQLCONVERTER_RELWITHDEBINFO_X32_H
#define VERSIONSQLCONVERTER_RELWITHDEBINFO_X32_H


  #define SQL_CONVERTER_BUILD_CX 9137
  #define SQL_CONVERTER_BUILD_CX_STR "Application build number: 9137"
  #define SQL_CONVERTER_MAJOR_VER 0
  #define SQL_CONVERTER_MINOR_VER 0
  #define SQL_CONVERTER_PATH_VER 2
  #define SQL_CONVERTER_INFO_VER_STR "SqlConverter version: 0.0.2 (9137)"

	

#endif