#ifndef VERSIONSQLCONVERTER_RELEASE_X32_H
#define VERSIONSQLCONVERTER_RELEASE_X32_H


  #define SQL_CONVERTER_BUILD_CX 9201
  #define SQL_CONVERTER_BUILD_CX_STR "Application build number: 9201"
  #define SQL_CONVERTER_MAJOR_VER 0
  #define SQL_CONVERTER_MINOR_VER 0
  #define SQL_CONVERTER_PATH_VER 2
  #define SQL_CONVERTER_INFO_VER_STR "SqlConverter version: 0.0.2 (9201)"

	

#endif